apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: transaction-management
  name: transaction-management
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: transaction-management
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: transaction-management
    spec:
      containers:
        - command:
            - /bin/bash
            - -c
            - cd /app && java -jar app.jar
          image: ccr.ccs.tencentyun.com/tsf_100006645002/bank:v1
          imagePullPolicy: Always
          name: transaction-management
          resources:
            limits:
              cpu: 8000m
              memory: 16Gi
            requests:
              cpu: 8000m
              memory: 16Gi
          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: qcloudregistrykey
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60


